id: P005520
initial_creation_type: ocr
source_metadata:
  id: bdr:W30426
  title: དེབ་ཐེར་དཀར་པོ
  author: ''
  volumes:
    f0c47117cddf4dc9a626b0faceb90591:
      image_group_id: I1PD30303
      title: ''
      volume_number: 1
      total_pages: 132
      base_file: v001.txt
